language: csharp
mono: none
dotnet: 2.0.0
install:
  - dotnet restore
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - dotnet build
  - dotnet test Polynomial.Demoscene.DemozooApi.Tests.DotNetCore/Polynomial.Demoscene.DemozooApi.Tests.DotNetCore.csproj
