version: '1.0.{build}'
image:
  - Visual Studio 2017
  - Ubuntu
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - sh: uname -a
  - dotnet --version
  - dotnet restore --verbosity m
build_script:
  - cmd: dotnet build
  - sh: dotnet build -f netstandard2.0
after_build:
test_script:
  - cmd dotnet test Polynomial.Demoscene.DemozooApi.Tests.DotNetCore/Polynomial.Demoscene.DemozooApi.Tests.DotNetCore.csproj
  - sh dotnet test -f netstandard2.0 Polynomial.Demoscene.DemozooApi.Tests.DotNetCore/Polynomial.Demoscene.DemozooApi.Tests.DotNetCore.csproj
on_finish:
  # any cleanup in here
deploy: off
